name: B
on:
  workflow_call:
jobs:
  b:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Echo var
        run: echo ${{ var.test }}
      - name: Echo secret
        run: echo ${{ sercets.secret }}
